# Generated by Django 4.2.30 on 2026-07-10 15:10

from django.db import migrations, models
import djsuperadmin.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=200, unique=True)),
                ("content", models.TextField()),
            ],
            bases=(models.Model, djsuperadmin.mixins.DjSuperAdminMixin),
        ),
        migrations.CreateModel(
            name="ContentWithoutUrls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=200, unique=True)),
                ("content", models.TextField()),
            ],
            bases=(models.Model, djsuperadmin.mixins.DjSuperAdminMixin),
        ),
    ]
