# Generated by Django 4.1.7 on 2023-05-02 06:36

from django.db import migrations, models
import djsuperadmin.mixins
import djsuperadmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.CharField(default=djsuperadmin.models.make_random_id, editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            bases=(models.Model, djsuperadmin.mixins.DjSuperAdminMixin),
        ),
    ]
