# Generated by Django 2.2.1 on 2019-06-10 13:03

from django.db import migrations
import django.db.models.deletion
import hvad.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djsuperadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='_hvad_query',
            field=hvad.fields.SingleTranslationObject('djsuperadmin.Content', 'djsuperadmin.ContentTranslation'),
        ),
        migrations.AlterField(
            model_name='contenttranslation',
            name='master',
            field=hvad.fields.MasterKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='djsuperadmin.Content'),
        ),
    ]
